import { Link } from 'react-router-dom'
import { ArrowUpRight, BookOpen, Clock3 } from 'lucide-react'

const posts = [
  { tag:'DROP', title:'Como uma coleção nasce de uma ideia', text:'Do primeiro rabisco à peça que entra para a tripulação: um olhar sobre o processo criativo da Kosmo Roll.', date:'Diário de Bordo · 01', image:'/products/alien-joia-front.webp' },
  { tag:'CULTURA', title:'Fora de órbita por design', text:'Streetwear também é linguagem. Estética, atitude e identidade para quem prefere criar a própria rota.', date:'Diário de Bordo · 02', image:'/products/alien-verde-front.webp' },
  { tag:'UNIVERSO', title:'Por que o cosmos combina com a rua?', text:'Planetas, contrastes, alienígenas e o imaginário que transforma o cotidiano em território de criação.', date:'Diário de Bordo · 03', image:'/products/olhos-coloridos-front.webp' },
]
export default function Diario() { return <div className="min-h-screen py-16 px-4 sm:px-6"><div className="max-w-6xl mx-auto"><div className="max-w-2xl mb-12"><div className="inline-flex items-center gap-2 text-kosmo text-xs font-bold uppercase tracking-[.2em]"><BookOpen size={15}/> Diário de Bordo</div><h1 className="font-display text-4xl sm:text-6xl font-bold text-cosmos mt-3">Histórias da <span className="text-gradient">tripulação.</span></h1><p className="text-cosmos/60 mt-4">Drops, processo criativo, cultura urbana e referências que vivem por trás das peças.</p></div><div className="grid md:grid-cols-3 gap-6">{posts.map(post=><article key={post.title} className="group rounded-3xl overflow-hidden border border-gray-200 dark:border-white/10 bg-white/70 dark:bg-white/5"><div className="aspect-[4/3] overflow-hidden"><img src={post.image} alt="" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"/></div><div className="p-6"><span className="text-[10px] font-bold tracking-[.2em] text-kosmo">{post.tag}</span><h2 className="font-display text-xl font-bold text-cosmos mt-3">{post.title}</h2><p className="text-sm text-cosmos/50 leading-relaxed mt-3">{post.text}</p><div className="flex items-center justify-between mt-6 pt-4 border-t border-gray-100 dark:border-white/10"><span className="text-xs text-cosmos/40 flex items-center gap-1"><Clock3 size={13}/> 4 min</span><Link to="/sobre" className="text-xs font-bold text-kosmo flex items-center gap-1">Ler história <ArrowUpRight size={13}/></Link></div></div></article>)}</div></div></div> }
