import { motion } from 'framer-motion'
import { Camera, Play } from 'lucide-react'

const moments = [
  { title:'A ideia ganha forma', image:'/products/alien-joia-front.webp', type:'Conceito' },
  { title:'Detalhes que contam', image:'/products/alien-joia-back.webp', type:'Estampa' },
  { title:'A peça em outra órbita', image:'/products/alien-verde-front.webp', type:'Produto' },
  { title:'Cores da missão', image:'/products/olhos-coloridos-front.webp', type:'Direção de arte' },
]
export default function MakingOf() { return <div className="min-h-screen py-16 px-4 sm:px-6"><div className="max-w-6xl mx-auto"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-12"><div><div className="inline-flex items-center gap-2 text-kosmo text-xs font-bold uppercase tracking-[.2em]"><Camera size={15}/> Making Of</div><h1 className="font-display text-4xl sm:text-6xl font-bold text-cosmos mt-3">Antes da <span className="text-gradient">órbita.</span></h1><p className="text-cosmos/60 max-w-2xl mt-4">Uma galeria dedicada aos detalhes, referências e processos que formam cada drop.</p></div><div className="flex items-center gap-2 text-xs text-cosmos/40"><Play size={14}/> Bastidores da criação</div></div><div className="grid sm:grid-cols-2 gap-5">{moments.map((item,index)=><motion.figure key={item.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} className={`group relative overflow-hidden rounded-3xl ${index===0?'sm:row-span-2':''}`}><img src={item.image} alt={item.title} className="w-full h-full min-h-64 object-cover group-hover:scale-105 transition-transform duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><figcaption className="absolute left-5 right-5 bottom-5 text-white"><span className="text-[10px] uppercase tracking-[.2em] text-white/60">{item.type}</span><h2 className="font-display text-xl font-bold mt-1">{item.title}</h2></figcaption></motion.figure>)}</div><p className="text-center text-xs text-cosmos/40 mt-10">Mais registros de produção podem entrar aqui conforme novos drops forem criados.</p></div></div> }
