import { useState } from 'react'
import { Copy, Check, Share2, Gift, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'

const code = 'KOSMO-' + 'ORBITA'
export default function Referral() {
  const [copied, setCopied] = useState(false)
  const link = typeof window !== 'undefined' ? `${window.location.origin}/cadastro?ref=${code}` : `/cadastro?ref=${code}`
  const copy = async () => { await navigator.clipboard?.writeText(link); setCopied(true); setTimeout(()=>setCopied(false),1800) }
  const share = async () => { if (navigator.share) await navigator.share({ title:'Entra na órbita da Kosmo Roll', text:'Use meu convite e descubra a Kosmo Roll.', url:link }); else copy() }
  return <div className="min-h-screen py-20 px-4"><div className="max-w-4xl mx-auto text-center"><div className="inline-flex p-4 rounded-3xl bg-kosmo/10 text-kosmo mb-5"><Gift size={28}/></div><p className="text-kosmo text-xs font-bold uppercase tracking-[.25em]">Kosmo Crew</p><h1 className="font-display text-4xl sm:text-6xl font-bold text-cosmos mt-3">Indique. Convide. <span className="text-gradient">Ganhe.</span></h1><p className="text-cosmos/60 max-w-2xl mx-auto mt-5">Compartilhe sua órbita com alguém. O convidado recebe uma condição especial e você acumula benefício para a próxima missão.</p><div className="grid sm:grid-cols-3 gap-4 mt-12 text-left">{[['01','Envie','Compartilhe seu link pessoal.'],['02','Seu amigo compra','O convite é aplicado na primeira compra.'],['03','Você ganha','Seu benefício fica disponível para a próxima compra.']].map(([n,t,d])=><div key={n} className="rounded-3xl border border-gray-200 dark:border-white/10 p-6 bg-white/70 dark:bg-white/5"><span className="text-kosmo font-display font-bold">{n}</span><h2 className="font-display text-xl font-bold text-cosmos mt-4">{t}</h2><p className="text-sm text-cosmos/50 mt-2">{d}</p></div>)}</div><div className="mt-10 rounded-3xl bg-cosmos p-6 sm:p-8 text-left"><p className="text-xs uppercase tracking-widest text-white/40">Seu convite</p><div className="mt-3 flex flex-col sm:flex-row gap-3"><div className="flex-1 rounded-2xl bg-white/10 px-4 py-3 text-sm text-white/80 break-all">{link}</div><button onClick={copy} className="px-5 py-3 rounded-2xl bg-white text-cosmos font-semibold flex items-center justify-center gap-2">{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Copiado':'Copiar'}</button><button onClick={share} className="px-5 py-3 rounded-2xl bg-kosmo text-white font-semibold flex items-center justify-center gap-2"><Share2 size={17}/> Compartilhar</button></div></div><Link to="/catalogo" className="inline-flex items-center gap-2 mt-8 text-sm font-semibold text-kosmo">Voltar ao catálogo <ArrowRight size={15}/></Link></div></div>
}
